/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StatusRouteImport } from './routes/status'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as OperatorsRouteImport } from './routes/operators'
import { Route as MethodologyRouteImport } from './routes/methodology'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as DisclaimerRouteImport } from './routes/disclaimer'
import { Route as ChangelogRouteImport } from './routes/changelog'
import { Route as ApiRouteImport } from './routes/api'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiDocsRouteImport } from './routes/api.docs'
import { Route as AgentMintRouteImport } from './routes/agent.$mint'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as ApiPublicWebhookHeliusRouteImport } from './routes/api.public.webhook-helius'
import { Route as ApiPublicHeliusWebhookSetupRouteImport } from './routes/api.public.helius-webhook-setup'
import { Route as ApiPublicCronScoringRouteImport } from './routes/api.public.cron-scoring'
import { Route as ApiPublicCronReconcilerRouteImport } from './routes/api.public.cron-reconciler'
import { Route as ApiPublicCronBackfillRouteImport } from './routes/api.public.cron-backfill'
import { Route as AuthenticatedDashboardWatchlistRouteImport } from './routes/_authenticated.dashboard.watchlist'
import { Route as AuthenticatedDashboardApiKeysRouteImport } from './routes/_authenticated.dashboard.api-keys'
import { Route as AuthenticatedDashboardAlertsRouteImport } from './routes/_authenticated.dashboard.alerts'

const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const OperatorsRoute = OperatorsRouteImport.update({
  id: '/operators',
  path: '/operators',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodologyRoute = MethodologyRouteImport.update({
  id: '/methodology',
  path: '/methodology',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclaimerRoute = DisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogRoute = ChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRoute = ApiRouteImport.update({
  id: '/api',
  path: '/api',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDocsRoute = ApiDocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => ApiRoute,
} as any)
const AgentMintRoute = AgentMintRouteImport.update({
  id: '/agent/$mint',
  path: '/agent/$mint',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiPublicWebhookHeliusRoute = ApiPublicWebhookHeliusRouteImport.update({
  id: '/public/webhook-helius',
  path: '/public/webhook-helius',
  getParentRoute: () => ApiRoute,
} as any)
const ApiPublicHeliusWebhookSetupRoute =
  ApiPublicHeliusWebhookSetupRouteImport.update({
    id: '/public/helius-webhook-setup',
    path: '/public/helius-webhook-setup',
    getParentRoute: () => ApiRoute,
  } as any)
const ApiPublicCronScoringRoute = ApiPublicCronScoringRouteImport.update({
  id: '/public/cron-scoring',
  path: '/public/cron-scoring',
  getParentRoute: () => ApiRoute,
} as any)
const ApiPublicCronReconcilerRoute = ApiPublicCronReconcilerRouteImport.update({
  id: '/public/cron-reconciler',
  path: '/public/cron-reconciler',
  getParentRoute: () => ApiRoute,
} as any)
const ApiPublicCronBackfillRoute = ApiPublicCronBackfillRouteImport.update({
  id: '/public/cron-backfill',
  path: '/public/cron-backfill',
  getParentRoute: () => ApiRoute,
} as any)
const AuthenticatedDashboardWatchlistRoute =
  AuthenticatedDashboardWatchlistRouteImport.update({
    id: '/watchlist',
    path: '/watchlist',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardApiKeysRoute =
  AuthenticatedDashboardApiKeysRouteImport.update({
    id: '/api-keys',
    path: '/api-keys',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardAlertsRoute =
  AuthenticatedDashboardAlertsRouteImport.update({
    id: '/alerts',
    path: '/alerts',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/alerts': typeof AlertsRoute
  '/api': typeof ApiRouteWithChildren
  '/changelog': typeof ChangelogRoute
  '/disclaimer': typeof DisclaimerRoute
  '/explore': typeof ExploreRoute
  '/login': typeof LoginRoute
  '/methodology': typeof MethodologyRoute
  '/operators': typeof OperatorsRoute
  '/pricing': typeof PricingRoute
  '/signup': typeof SignupRoute
  '/status': typeof StatusRoute
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/agent/$mint': typeof AgentMintRoute
  '/api/docs': typeof ApiDocsRoute
  '/dashboard/alerts': typeof AuthenticatedDashboardAlertsRoute
  '/dashboard/api-keys': typeof AuthenticatedDashboardApiKeysRoute
  '/dashboard/watchlist': typeof AuthenticatedDashboardWatchlistRoute
  '/api/public/cron-backfill': typeof ApiPublicCronBackfillRoute
  '/api/public/cron-reconciler': typeof ApiPublicCronReconcilerRoute
  '/api/public/cron-scoring': typeof ApiPublicCronScoringRoute
  '/api/public/helius-webhook-setup': typeof ApiPublicHeliusWebhookSetupRoute
  '/api/public/webhook-helius': typeof ApiPublicWebhookHeliusRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/alerts': typeof AlertsRoute
  '/api': typeof ApiRouteWithChildren
  '/changelog': typeof ChangelogRoute
  '/disclaimer': typeof DisclaimerRoute
  '/explore': typeof ExploreRoute
  '/login': typeof LoginRoute
  '/methodology': typeof MethodologyRoute
  '/operators': typeof OperatorsRoute
  '/pricing': typeof PricingRoute
  '/signup': typeof SignupRoute
  '/status': typeof StatusRoute
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/agent/$mint': typeof AgentMintRoute
  '/api/docs': typeof ApiDocsRoute
  '/dashboard/alerts': typeof AuthenticatedDashboardAlertsRoute
  '/dashboard/api-keys': typeof AuthenticatedDashboardApiKeysRoute
  '/dashboard/watchlist': typeof AuthenticatedDashboardWatchlistRoute
  '/api/public/cron-backfill': typeof ApiPublicCronBackfillRoute
  '/api/public/cron-reconciler': typeof ApiPublicCronReconcilerRoute
  '/api/public/cron-scoring': typeof ApiPublicCronScoringRoute
  '/api/public/helius-webhook-setup': typeof ApiPublicHeliusWebhookSetupRoute
  '/api/public/webhook-helius': typeof ApiPublicWebhookHeliusRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/alerts': typeof AlertsRoute
  '/api': typeof ApiRouteWithChildren
  '/changelog': typeof ChangelogRoute
  '/disclaimer': typeof DisclaimerRoute
  '/explore': typeof ExploreRoute
  '/login': typeof LoginRoute
  '/methodology': typeof MethodologyRoute
  '/operators': typeof OperatorsRoute
  '/pricing': typeof PricingRoute
  '/signup': typeof SignupRoute
  '/status': typeof StatusRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/agent/$mint': typeof AgentMintRoute
  '/api/docs': typeof ApiDocsRoute
  '/_authenticated/dashboard/alerts': typeof AuthenticatedDashboardAlertsRoute
  '/_authenticated/dashboard/api-keys': typeof AuthenticatedDashboardApiKeysRoute
  '/_authenticated/dashboard/watchlist': typeof AuthenticatedDashboardWatchlistRoute
  '/api/public/cron-backfill': typeof ApiPublicCronBackfillRoute
  '/api/public/cron-reconciler': typeof ApiPublicCronReconcilerRoute
  '/api/public/cron-scoring': typeof ApiPublicCronScoringRoute
  '/api/public/helius-webhook-setup': typeof ApiPublicHeliusWebhookSetupRoute
  '/api/public/webhook-helius': typeof ApiPublicWebhookHeliusRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/alerts'
    | '/api'
    | '/changelog'
    | '/disclaimer'
    | '/explore'
    | '/login'
    | '/methodology'
    | '/operators'
    | '/pricing'
    | '/signup'
    | '/status'
    | '/dashboard'
    | '/agent/$mint'
    | '/api/docs'
    | '/dashboard/alerts'
    | '/dashboard/api-keys'
    | '/dashboard/watchlist'
    | '/api/public/cron-backfill'
    | '/api/public/cron-reconciler'
    | '/api/public/cron-scoring'
    | '/api/public/helius-webhook-setup'
    | '/api/public/webhook-helius'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/alerts'
    | '/api'
    | '/changelog'
    | '/disclaimer'
    | '/explore'
    | '/login'
    | '/methodology'
    | '/operators'
    | '/pricing'
    | '/signup'
    | '/status'
    | '/dashboard'
    | '/agent/$mint'
    | '/api/docs'
    | '/dashboard/alerts'
    | '/dashboard/api-keys'
    | '/dashboard/watchlist'
    | '/api/public/cron-backfill'
    | '/api/public/cron-reconciler'
    | '/api/public/cron-scoring'
    | '/api/public/helius-webhook-setup'
    | '/api/public/webhook-helius'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/alerts'
    | '/api'
    | '/changelog'
    | '/disclaimer'
    | '/explore'
    | '/login'
    | '/methodology'
    | '/operators'
    | '/pricing'
    | '/signup'
    | '/status'
    | '/_authenticated/dashboard'
    | '/agent/$mint'
    | '/api/docs'
    | '/_authenticated/dashboard/alerts'
    | '/_authenticated/dashboard/api-keys'
    | '/_authenticated/dashboard/watchlist'
    | '/api/public/cron-backfill'
    | '/api/public/cron-reconciler'
    | '/api/public/cron-scoring'
    | '/api/public/helius-webhook-setup'
    | '/api/public/webhook-helius'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  AlertsRoute: typeof AlertsRoute
  ApiRoute: typeof ApiRouteWithChildren
  ChangelogRoute: typeof ChangelogRoute
  DisclaimerRoute: typeof DisclaimerRoute
  ExploreRoute: typeof ExploreRoute
  LoginRoute: typeof LoginRoute
  MethodologyRoute: typeof MethodologyRoute
  OperatorsRoute: typeof OperatorsRoute
  PricingRoute: typeof PricingRoute
  SignupRoute: typeof SignupRoute
  StatusRoute: typeof StatusRoute
  AgentMintRoute: typeof AgentMintRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operators': {
      id: '/operators'
      path: '/operators'
      fullPath: '/operators'
      preLoaderRoute: typeof OperatorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/methodology': {
      id: '/methodology'
      path: '/methodology'
      fullPath: '/methodology'
      preLoaderRoute: typeof MethodologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimer': {
      id: '/disclaimer'
      path: '/disclaimer'
      fullPath: '/disclaimer'
      preLoaderRoute: typeof DisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog': {
      id: '/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof ChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api': {
      id: '/api'
      path: '/api'
      fullPath: '/api'
      preLoaderRoute: typeof ApiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/docs': {
      id: '/api/docs'
      path: '/docs'
      fullPath: '/api/docs'
      preLoaderRoute: typeof ApiDocsRouteImport
      parentRoute: typeof ApiRoute
    }
    '/agent/$mint': {
      id: '/agent/$mint'
      path: '/agent/$mint'
      fullPath: '/agent/$mint'
      preLoaderRoute: typeof AgentMintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/webhook-helius': {
      id: '/api/public/webhook-helius'
      path: '/public/webhook-helius'
      fullPath: '/api/public/webhook-helius'
      preLoaderRoute: typeof ApiPublicWebhookHeliusRouteImport
      parentRoute: typeof ApiRoute
    }
    '/api/public/helius-webhook-setup': {
      id: '/api/public/helius-webhook-setup'
      path: '/public/helius-webhook-setup'
      fullPath: '/api/public/helius-webhook-setup'
      preLoaderRoute: typeof ApiPublicHeliusWebhookSetupRouteImport
      parentRoute: typeof ApiRoute
    }
    '/api/public/cron-scoring': {
      id: '/api/public/cron-scoring'
      path: '/public/cron-scoring'
      fullPath: '/api/public/cron-scoring'
      preLoaderRoute: typeof ApiPublicCronScoringRouteImport
      parentRoute: typeof ApiRoute
    }
    '/api/public/cron-reconciler': {
      id: '/api/public/cron-reconciler'
      path: '/public/cron-reconciler'
      fullPath: '/api/public/cron-reconciler'
      preLoaderRoute: typeof ApiPublicCronReconcilerRouteImport
      parentRoute: typeof ApiRoute
    }
    '/api/public/cron-backfill': {
      id: '/api/public/cron-backfill'
      path: '/public/cron-backfill'
      fullPath: '/api/public/cron-backfill'
      preLoaderRoute: typeof ApiPublicCronBackfillRouteImport
      parentRoute: typeof ApiRoute
    }
    '/_authenticated/dashboard/watchlist': {
      id: '/_authenticated/dashboard/watchlist'
      path: '/watchlist'
      fullPath: '/dashboard/watchlist'
      preLoaderRoute: typeof AuthenticatedDashboardWatchlistRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/api-keys': {
      id: '/_authenticated/dashboard/api-keys'
      path: '/api-keys'
      fullPath: '/dashboard/api-keys'
      preLoaderRoute: typeof AuthenticatedDashboardApiKeysRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/alerts': {
      id: '/_authenticated/dashboard/alerts'
      path: '/alerts'
      fullPath: '/dashboard/alerts'
      preLoaderRoute: typeof AuthenticatedDashboardAlertsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
  }
}

interface AuthenticatedDashboardRouteChildren {
  AuthenticatedDashboardAlertsRoute: typeof AuthenticatedDashboardAlertsRoute
  AuthenticatedDashboardApiKeysRoute: typeof AuthenticatedDashboardApiKeysRoute
  AuthenticatedDashboardWatchlistRoute: typeof AuthenticatedDashboardWatchlistRoute
}

const AuthenticatedDashboardRouteChildren: AuthenticatedDashboardRouteChildren =
  {
    AuthenticatedDashboardAlertsRoute: AuthenticatedDashboardAlertsRoute,
    AuthenticatedDashboardApiKeysRoute: AuthenticatedDashboardApiKeysRoute,
    AuthenticatedDashboardWatchlistRoute: AuthenticatedDashboardWatchlistRoute,
  }

const AuthenticatedDashboardRouteWithChildren =
  AuthenticatedDashboardRoute._addFileChildren(
    AuthenticatedDashboardRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface ApiRouteChildren {
  ApiDocsRoute: typeof ApiDocsRoute
  ApiPublicCronBackfillRoute: typeof ApiPublicCronBackfillRoute
  ApiPublicCronReconcilerRoute: typeof ApiPublicCronReconcilerRoute
  ApiPublicCronScoringRoute: typeof ApiPublicCronScoringRoute
  ApiPublicHeliusWebhookSetupRoute: typeof ApiPublicHeliusWebhookSetupRoute
  ApiPublicWebhookHeliusRoute: typeof ApiPublicWebhookHeliusRoute
}

const ApiRouteChildren: ApiRouteChildren = {
  ApiDocsRoute: ApiDocsRoute,
  ApiPublicCronBackfillRoute: ApiPublicCronBackfillRoute,
  ApiPublicCronReconcilerRoute: ApiPublicCronReconcilerRoute,
  ApiPublicCronScoringRoute: ApiPublicCronScoringRoute,
  ApiPublicHeliusWebhookSetupRoute: ApiPublicHeliusWebhookSetupRoute,
  ApiPublicWebhookHeliusRoute: ApiPublicWebhookHeliusRoute,
}

const ApiRouteWithChildren = ApiRoute._addFileChildren(ApiRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  AlertsRoute: AlertsRoute,
  ApiRoute: ApiRouteWithChildren,
  ChangelogRoute: ChangelogRoute,
  DisclaimerRoute: DisclaimerRoute,
  ExploreRoute: ExploreRoute,
  LoginRoute: LoginRoute,
  MethodologyRoute: MethodologyRoute,
  OperatorsRoute: OperatorsRoute,
  PricingRoute: PricingRoute,
  SignupRoute: SignupRoute,
  StatusRoute: StatusRoute,
  AgentMintRoute: AgentMintRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
