/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TapeRouteImport } from './routes/tape'
import { Route as SubmitRouteImport } from './routes/submit'
import { Route as StatusRouteImport } from './routes/status'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as OperatorsRouteImport } from './routes/operators'
import { Route as MethodologyRouteImport } from './routes/methodology'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as FlaggedRouteImport } from './routes/flagged'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as DisclaimerRouteImport } from './routes/disclaimer'
import { Route as ChangelogRouteImport } from './routes/changelog'
import { Route as ApiRouteImport } from './routes/api'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TapeEventIdRouteImport } from './routes/tape.$eventId'
import { Route as ApiDocsRouteImport } from './routes/api.docs'
import { Route as AgentMintRouteImport } from './routes/agent.$mint'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as ApiPublicWebhookHeliusRouteImport } from './routes/api.public.webhook-helius'
import { Route as ApiPublicHeliusWebhookSetupRouteImport } from './routes/api.public.helius-webhook-setup'
import { Route as ApiPublicCronVerifyCandidatesRouteImport } from './routes/api.public.cron-verify-candidates'
import { Route as ApiPublicCronScoringRouteImport } from './routes/api.public.cron-scoring'
import { Route as ApiPublicCronScanX402RouteImport } from './routes/api.public.cron-scan-x402'
import { Route as ApiPublicCronScanAgentRegistryRouteImport } from './routes/api.public.cron-scan-agent-registry'
import { Route as ApiPublicCronReconcilerRouteImport } from './routes/api.public.cron-reconciler'
import { Route as ApiPublicCronFailureReconcilerRouteImport } from './routes/api.public.cron-failure-reconciler'
import { Route as ApiPublicCronBackfillRouteImport } from './routes/api.public.cron-backfill'
import { Route as AuthenticatedDashboardWatchlistRouteImport } from './routes/_authenticated.dashboard.watchlist'
import { Route as AuthenticatedDashboardApiKeysRouteImport } from './routes/_authenticated.dashboard.api-keys'
import { Route as AuthenticatedDashboardAlertsRouteImport } from './routes/_authenticated.dashboard.alerts'
import { Route as ApiPublicBadgeChar123mintChar125DotsvgRouteImport } from './routes/api.public.badge.{$mint}[.]svg'

const TapeRoute = TapeRouteImport.update({
  id: '/tape',
  path: '/tape',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmitRoute = SubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const OperatorsRoute = OperatorsRouteImport.update({
  id: '/operators',
  path: '/operators',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodologyRoute = MethodologyRouteImport.update({
  id: '/methodology',
  path: '/methodology',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const FlaggedRoute = FlaggedRouteImport.update({
  id: '/flagged',
  path: '/flagged',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclaimerRoute = DisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogRoute = ChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRoute = ApiRouteImport.update({
  id: '/api',
  path: '/api',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TapeEventIdRoute = TapeEventIdRouteImport.update({
  id: '/$eventId',
  path: '/$eventId',
  getParentRoute: () => TapeRoute,
} as any)
const ApiDocsRoute = ApiDocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => ApiRoute,
} as any)
const AgentMintRoute = AgentMintRouteImport.update({
  id: '/agent/$mint',
  path: '/agent/$mint',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiPublicWebhookHeliusRoute = ApiPublicWebhookHeliusRouteImport.update({
  id: '/public/webhook-helius',
  path: '/public/webhook-helius',
  getParentRoute: () => ApiRoute,
} as any)
const ApiPublicHeliusWebhookSetupRoute =
  ApiPublicHeliusWebhookSetupRouteImport.update({
    id: '/public/helius-webhook-setup',
    path: '/public/helius-webhook-setup',
    getParentRoute: () => ApiRoute,
  } as any)
const ApiPublicCronVerifyCandidatesRoute =
  ApiPublicCronVerifyCandidatesRouteImport.update({
    id: '/public/cron-verify-candidates',
    path: '/public/cron-verify-candidates',
    getParentRoute: () => ApiRoute,
  } as any)
const ApiPublicCronScoringRoute = ApiPublicCronScoringRouteImport.update({
  id: '/public/cron-scoring',
  path: '/public/cron-scoring',
  getParentRoute: () => ApiRoute,
} as any)
const ApiPublicCronScanX402Route = ApiPublicCronScanX402RouteImport.update({
  id: '/public/cron-scan-x402',
  path: '/public/cron-scan-x402',
  getParentRoute: () => ApiRoute,
} as any)
const ApiPublicCronScanAgentRegistryRoute =
  ApiPublicCronScanAgentRegistryRouteImport.update({
    id: '/public/cron-scan-agent-registry',
    path: '/public/cron-scan-agent-registry',
    getParentRoute: () => ApiRoute,
  } as any)
const ApiPublicCronReconcilerRoute = ApiPublicCronReconcilerRouteImport.update({
  id: '/public/cron-reconciler',
  path: '/public/cron-reconciler',
  getParentRoute: () => ApiRoute,
} as any)
const ApiPublicCronFailureReconcilerRoute =
  ApiPublicCronFailureReconcilerRouteImport.update({
    id: '/public/cron-failure-reconciler',
    path: '/public/cron-failure-reconciler',
    getParentRoute: () => ApiRoute,
  } as any)
const ApiPublicCronBackfillRoute = ApiPublicCronBackfillRouteImport.update({
  id: '/public/cron-backfill',
  path: '/public/cron-backfill',
  getParentRoute: () => ApiRoute,
} as any)
const AuthenticatedDashboardWatchlistRoute =
  AuthenticatedDashboardWatchlistRouteImport.update({
    id: '/watchlist',
    path: '/watchlist',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardApiKeysRoute =
  AuthenticatedDashboardApiKeysRouteImport.update({
    id: '/api-keys',
    path: '/api-keys',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardAlertsRoute =
  AuthenticatedDashboardAlertsRouteImport.update({
    id: '/alerts',
    path: '/alerts',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const ApiPublicBadgeChar123mintChar125DotsvgRoute =
  ApiPublicBadgeChar123mintChar125DotsvgRouteImport.update({
    id: '/public/badge/{$mint}.svg',
    path: '/public/badge/{$mint}.svg',
    getParentRoute: () => ApiRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/alerts': typeof AlertsRoute
  '/api': typeof ApiRouteWithChildren
  '/changelog': typeof ChangelogRoute
  '/disclaimer': typeof DisclaimerRoute
  '/explore': typeof ExploreRoute
  '/flagged': typeof FlaggedRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/methodology': typeof MethodologyRoute
  '/operators': typeof OperatorsRoute
  '/pricing': typeof PricingRoute
  '/register': typeof RegisterRoute
  '/signup': typeof SignupRoute
  '/status': typeof StatusRoute
  '/submit': typeof SubmitRoute
  '/tape': typeof TapeRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/agent/$mint': typeof AgentMintRoute
  '/api/docs': typeof ApiDocsRoute
  '/tape/$eventId': typeof TapeEventIdRoute
  '/dashboard/alerts': typeof AuthenticatedDashboardAlertsRoute
  '/dashboard/api-keys': typeof AuthenticatedDashboardApiKeysRoute
  '/dashboard/watchlist': typeof AuthenticatedDashboardWatchlistRoute
  '/api/public/cron-backfill': typeof ApiPublicCronBackfillRoute
  '/api/public/cron-failure-reconciler': typeof ApiPublicCronFailureReconcilerRoute
  '/api/public/cron-reconciler': typeof ApiPublicCronReconcilerRoute
  '/api/public/cron-scan-agent-registry': typeof ApiPublicCronScanAgentRegistryRoute
  '/api/public/cron-scan-x402': typeof ApiPublicCronScanX402Route
  '/api/public/cron-scoring': typeof ApiPublicCronScoringRoute
  '/api/public/cron-verify-candidates': typeof ApiPublicCronVerifyCandidatesRoute
  '/api/public/helius-webhook-setup': typeof ApiPublicHeliusWebhookSetupRoute
  '/api/public/webhook-helius': typeof ApiPublicWebhookHeliusRoute
  '/api/public/badge/{$mint}.svg': typeof ApiPublicBadgeChar123mintChar125DotsvgRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/alerts': typeof AlertsRoute
  '/api': typeof ApiRouteWithChildren
  '/changelog': typeof ChangelogRoute
  '/disclaimer': typeof DisclaimerRoute
  '/explore': typeof ExploreRoute
  '/flagged': typeof FlaggedRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/methodology': typeof MethodologyRoute
  '/operators': typeof OperatorsRoute
  '/pricing': typeof PricingRoute
  '/register': typeof RegisterRoute
  '/signup': typeof SignupRoute
  '/status': typeof StatusRoute
  '/submit': typeof SubmitRoute
  '/tape': typeof TapeRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/agent/$mint': typeof AgentMintRoute
  '/api/docs': typeof ApiDocsRoute
  '/tape/$eventId': typeof TapeEventIdRoute
  '/dashboard/alerts': typeof AuthenticatedDashboardAlertsRoute
  '/dashboard/api-keys': typeof AuthenticatedDashboardApiKeysRoute
  '/dashboard/watchlist': typeof AuthenticatedDashboardWatchlistRoute
  '/api/public/cron-backfill': typeof ApiPublicCronBackfillRoute
  '/api/public/cron-failure-reconciler': typeof ApiPublicCronFailureReconcilerRoute
  '/api/public/cron-reconciler': typeof ApiPublicCronReconcilerRoute
  '/api/public/cron-scan-agent-registry': typeof ApiPublicCronScanAgentRegistryRoute
  '/api/public/cron-scan-x402': typeof ApiPublicCronScanX402Route
  '/api/public/cron-scoring': typeof ApiPublicCronScoringRoute
  '/api/public/cron-verify-candidates': typeof ApiPublicCronVerifyCandidatesRoute
  '/api/public/helius-webhook-setup': typeof ApiPublicHeliusWebhookSetupRoute
  '/api/public/webhook-helius': typeof ApiPublicWebhookHeliusRoute
  '/api/public/badge/{$mint}.svg': typeof ApiPublicBadgeChar123mintChar125DotsvgRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/alerts': typeof AlertsRoute
  '/api': typeof ApiRouteWithChildren
  '/changelog': typeof ChangelogRoute
  '/disclaimer': typeof DisclaimerRoute
  '/explore': typeof ExploreRoute
  '/flagged': typeof FlaggedRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/methodology': typeof MethodologyRoute
  '/operators': typeof OperatorsRoute
  '/pricing': typeof PricingRoute
  '/register': typeof RegisterRoute
  '/signup': typeof SignupRoute
  '/status': typeof StatusRoute
  '/submit': typeof SubmitRoute
  '/tape': typeof TapeRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/agent/$mint': typeof AgentMintRoute
  '/api/docs': typeof ApiDocsRoute
  '/tape/$eventId': typeof TapeEventIdRoute
  '/_authenticated/dashboard/alerts': typeof AuthenticatedDashboardAlertsRoute
  '/_authenticated/dashboard/api-keys': typeof AuthenticatedDashboardApiKeysRoute
  '/_authenticated/dashboard/watchlist': typeof AuthenticatedDashboardWatchlistRoute
  '/api/public/cron-backfill': typeof ApiPublicCronBackfillRoute
  '/api/public/cron-failure-reconciler': typeof ApiPublicCronFailureReconcilerRoute
  '/api/public/cron-reconciler': typeof ApiPublicCronReconcilerRoute
  '/api/public/cron-scan-agent-registry': typeof ApiPublicCronScanAgentRegistryRoute
  '/api/public/cron-scan-x402': typeof ApiPublicCronScanX402Route
  '/api/public/cron-scoring': typeof ApiPublicCronScoringRoute
  '/api/public/cron-verify-candidates': typeof ApiPublicCronVerifyCandidatesRoute
  '/api/public/helius-webhook-setup': typeof ApiPublicHeliusWebhookSetupRoute
  '/api/public/webhook-helius': typeof ApiPublicWebhookHeliusRoute
  '/api/public/badge/{$mint}.svg': typeof ApiPublicBadgeChar123mintChar125DotsvgRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/alerts'
    | '/api'
    | '/changelog'
    | '/disclaimer'
    | '/explore'
    | '/flagged'
    | '/leaderboard'
    | '/login'
    | '/methodology'
    | '/operators'
    | '/pricing'
    | '/register'
    | '/signup'
    | '/status'
    | '/submit'
    | '/tape'
    | '/dashboard'
    | '/agent/$mint'
    | '/api/docs'
    | '/tape/$eventId'
    | '/dashboard/alerts'
    | '/dashboard/api-keys'
    | '/dashboard/watchlist'
    | '/api/public/cron-backfill'
    | '/api/public/cron-failure-reconciler'
    | '/api/public/cron-reconciler'
    | '/api/public/cron-scan-agent-registry'
    | '/api/public/cron-scan-x402'
    | '/api/public/cron-scoring'
    | '/api/public/cron-verify-candidates'
    | '/api/public/helius-webhook-setup'
    | '/api/public/webhook-helius'
    | '/api/public/badge/{$mint}.svg'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/alerts'
    | '/api'
    | '/changelog'
    | '/disclaimer'
    | '/explore'
    | '/flagged'
    | '/leaderboard'
    | '/login'
    | '/methodology'
    | '/operators'
    | '/pricing'
    | '/register'
    | '/signup'
    | '/status'
    | '/submit'
    | '/tape'
    | '/dashboard'
    | '/agent/$mint'
    | '/api/docs'
    | '/tape/$eventId'
    | '/dashboard/alerts'
    | '/dashboard/api-keys'
    | '/dashboard/watchlist'
    | '/api/public/cron-backfill'
    | '/api/public/cron-failure-reconciler'
    | '/api/public/cron-reconciler'
    | '/api/public/cron-scan-agent-registry'
    | '/api/public/cron-scan-x402'
    | '/api/public/cron-scoring'
    | '/api/public/cron-verify-candidates'
    | '/api/public/helius-webhook-setup'
    | '/api/public/webhook-helius'
    | '/api/public/badge/{$mint}.svg'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/alerts'
    | '/api'
    | '/changelog'
    | '/disclaimer'
    | '/explore'
    | '/flagged'
    | '/leaderboard'
    | '/login'
    | '/methodology'
    | '/operators'
    | '/pricing'
    | '/register'
    | '/signup'
    | '/status'
    | '/submit'
    | '/tape'
    | '/_authenticated/dashboard'
    | '/agent/$mint'
    | '/api/docs'
    | '/tape/$eventId'
    | '/_authenticated/dashboard/alerts'
    | '/_authenticated/dashboard/api-keys'
    | '/_authenticated/dashboard/watchlist'
    | '/api/public/cron-backfill'
    | '/api/public/cron-failure-reconciler'
    | '/api/public/cron-reconciler'
    | '/api/public/cron-scan-agent-registry'
    | '/api/public/cron-scan-x402'
    | '/api/public/cron-scoring'
    | '/api/public/cron-verify-candidates'
    | '/api/public/helius-webhook-setup'
    | '/api/public/webhook-helius'
    | '/api/public/badge/{$mint}.svg'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  AlertsRoute: typeof AlertsRoute
  ApiRoute: typeof ApiRouteWithChildren
  ChangelogRoute: typeof ChangelogRoute
  DisclaimerRoute: typeof DisclaimerRoute
  ExploreRoute: typeof ExploreRoute
  FlaggedRoute: typeof FlaggedRoute
  LeaderboardRoute: typeof LeaderboardRoute
  LoginRoute: typeof LoginRoute
  MethodologyRoute: typeof MethodologyRoute
  OperatorsRoute: typeof OperatorsRoute
  PricingRoute: typeof PricingRoute
  RegisterRoute: typeof RegisterRoute
  SignupRoute: typeof SignupRoute
  StatusRoute: typeof StatusRoute
  SubmitRoute: typeof SubmitRoute
  TapeRoute: typeof TapeRouteWithChildren
  AgentMintRoute: typeof AgentMintRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tape': {
      id: '/tape'
      path: '/tape'
      fullPath: '/tape'
      preLoaderRoute: typeof TapeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submit': {
      id: '/submit'
      path: '/submit'
      fullPath: '/submit'
      preLoaderRoute: typeof SubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operators': {
      id: '/operators'
      path: '/operators'
      fullPath: '/operators'
      preLoaderRoute: typeof OperatorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/methodology': {
      id: '/methodology'
      path: '/methodology'
      fullPath: '/methodology'
      preLoaderRoute: typeof MethodologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flagged': {
      id: '/flagged'
      path: '/flagged'
      fullPath: '/flagged'
      preLoaderRoute: typeof FlaggedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimer': {
      id: '/disclaimer'
      path: '/disclaimer'
      fullPath: '/disclaimer'
      preLoaderRoute: typeof DisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog': {
      id: '/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof ChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api': {
      id: '/api'
      path: '/api'
      fullPath: '/api'
      preLoaderRoute: typeof ApiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tape/$eventId': {
      id: '/tape/$eventId'
      path: '/$eventId'
      fullPath: '/tape/$eventId'
      preLoaderRoute: typeof TapeEventIdRouteImport
      parentRoute: typeof TapeRoute
    }
    '/api/docs': {
      id: '/api/docs'
      path: '/docs'
      fullPath: '/api/docs'
      preLoaderRoute: typeof ApiDocsRouteImport
      parentRoute: typeof ApiRoute
    }
    '/agent/$mint': {
      id: '/agent/$mint'
      path: '/agent/$mint'
      fullPath: '/agent/$mint'
      preLoaderRoute: typeof AgentMintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/webhook-helius': {
      id: '/api/public/webhook-helius'
      path: '/public/webhook-helius'
      fullPath: '/api/public/webhook-helius'
      preLoaderRoute: typeof ApiPublicWebhookHeliusRouteImport
      parentRoute: typeof ApiRoute
    }
    '/api/public/helius-webhook-setup': {
      id: '/api/public/helius-webhook-setup'
      path: '/public/helius-webhook-setup'
      fullPath: '/api/public/helius-webhook-setup'
      preLoaderRoute: typeof ApiPublicHeliusWebhookSetupRouteImport
      parentRoute: typeof ApiRoute
    }
    '/api/public/cron-verify-candidates': {
      id: '/api/public/cron-verify-candidates'
      path: '/public/cron-verify-candidates'
      fullPath: '/api/public/cron-verify-candidates'
      preLoaderRoute: typeof ApiPublicCronVerifyCandidatesRouteImport
      parentRoute: typeof ApiRoute
    }
    '/api/public/cron-scoring': {
      id: '/api/public/cron-scoring'
      path: '/public/cron-scoring'
      fullPath: '/api/public/cron-scoring'
      preLoaderRoute: typeof ApiPublicCronScoringRouteImport
      parentRoute: typeof ApiRoute
    }
    '/api/public/cron-scan-x402': {
      id: '/api/public/cron-scan-x402'
      path: '/public/cron-scan-x402'
      fullPath: '/api/public/cron-scan-x402'
      preLoaderRoute: typeof ApiPublicCronScanX402RouteImport
      parentRoute: typeof ApiRoute
    }
    '/api/public/cron-scan-agent-registry': {
      id: '/api/public/cron-scan-agent-registry'
      path: '/public/cron-scan-agent-registry'
      fullPath: '/api/public/cron-scan-agent-registry'
      preLoaderRoute: typeof ApiPublicCronScanAgentRegistryRouteImport
      parentRoute: typeof ApiRoute
    }
    '/api/public/cron-reconciler': {
      id: '/api/public/cron-reconciler'
      path: '/public/cron-reconciler'
      fullPath: '/api/public/cron-reconciler'
      preLoaderRoute: typeof ApiPublicCronReconcilerRouteImport
      parentRoute: typeof ApiRoute
    }
    '/api/public/cron-failure-reconciler': {
      id: '/api/public/cron-failure-reconciler'
      path: '/public/cron-failure-reconciler'
      fullPath: '/api/public/cron-failure-reconciler'
      preLoaderRoute: typeof ApiPublicCronFailureReconcilerRouteImport
      parentRoute: typeof ApiRoute
    }
    '/api/public/cron-backfill': {
      id: '/api/public/cron-backfill'
      path: '/public/cron-backfill'
      fullPath: '/api/public/cron-backfill'
      preLoaderRoute: typeof ApiPublicCronBackfillRouteImport
      parentRoute: typeof ApiRoute
    }
    '/_authenticated/dashboard/watchlist': {
      id: '/_authenticated/dashboard/watchlist'
      path: '/watchlist'
      fullPath: '/dashboard/watchlist'
      preLoaderRoute: typeof AuthenticatedDashboardWatchlistRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/api-keys': {
      id: '/_authenticated/dashboard/api-keys'
      path: '/api-keys'
      fullPath: '/dashboard/api-keys'
      preLoaderRoute: typeof AuthenticatedDashboardApiKeysRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/alerts': {
      id: '/_authenticated/dashboard/alerts'
      path: '/alerts'
      fullPath: '/dashboard/alerts'
      preLoaderRoute: typeof AuthenticatedDashboardAlertsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/api/public/badge/{$mint}.svg': {
      id: '/api/public/badge/{$mint}.svg'
      path: '/public/badge/{$mint}.svg'
      fullPath: '/api/public/badge/{$mint}.svg'
      preLoaderRoute: typeof ApiPublicBadgeChar123mintChar125DotsvgRouteImport
      parentRoute: typeof ApiRoute
    }
  }
}

interface AuthenticatedDashboardRouteChildren {
  AuthenticatedDashboardAlertsRoute: typeof AuthenticatedDashboardAlertsRoute
  AuthenticatedDashboardApiKeysRoute: typeof AuthenticatedDashboardApiKeysRoute
  AuthenticatedDashboardWatchlistRoute: typeof AuthenticatedDashboardWatchlistRoute
}

const AuthenticatedDashboardRouteChildren: AuthenticatedDashboardRouteChildren =
  {
    AuthenticatedDashboardAlertsRoute: AuthenticatedDashboardAlertsRoute,
    AuthenticatedDashboardApiKeysRoute: AuthenticatedDashboardApiKeysRoute,
    AuthenticatedDashboardWatchlistRoute: AuthenticatedDashboardWatchlistRoute,
  }

const AuthenticatedDashboardRouteWithChildren =
  AuthenticatedDashboardRoute._addFileChildren(
    AuthenticatedDashboardRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface ApiRouteChildren {
  ApiDocsRoute: typeof ApiDocsRoute
  ApiPublicCronBackfillRoute: typeof ApiPublicCronBackfillRoute
  ApiPublicCronFailureReconcilerRoute: typeof ApiPublicCronFailureReconcilerRoute
  ApiPublicCronReconcilerRoute: typeof ApiPublicCronReconcilerRoute
  ApiPublicCronScanAgentRegistryRoute: typeof ApiPublicCronScanAgentRegistryRoute
  ApiPublicCronScanX402Route: typeof ApiPublicCronScanX402Route
  ApiPublicCronScoringRoute: typeof ApiPublicCronScoringRoute
  ApiPublicCronVerifyCandidatesRoute: typeof ApiPublicCronVerifyCandidatesRoute
  ApiPublicHeliusWebhookSetupRoute: typeof ApiPublicHeliusWebhookSetupRoute
  ApiPublicWebhookHeliusRoute: typeof ApiPublicWebhookHeliusRoute
  ApiPublicBadgeChar123mintChar125DotsvgRoute: typeof ApiPublicBadgeChar123mintChar125DotsvgRoute
}

const ApiRouteChildren: ApiRouteChildren = {
  ApiDocsRoute: ApiDocsRoute,
  ApiPublicCronBackfillRoute: ApiPublicCronBackfillRoute,
  ApiPublicCronFailureReconcilerRoute: ApiPublicCronFailureReconcilerRoute,
  ApiPublicCronReconcilerRoute: ApiPublicCronReconcilerRoute,
  ApiPublicCronScanAgentRegistryRoute: ApiPublicCronScanAgentRegistryRoute,
  ApiPublicCronScanX402Route: ApiPublicCronScanX402Route,
  ApiPublicCronScoringRoute: ApiPublicCronScoringRoute,
  ApiPublicCronVerifyCandidatesRoute: ApiPublicCronVerifyCandidatesRoute,
  ApiPublicHeliusWebhookSetupRoute: ApiPublicHeliusWebhookSetupRoute,
  ApiPublicWebhookHeliusRoute: ApiPublicWebhookHeliusRoute,
  ApiPublicBadgeChar123mintChar125DotsvgRoute:
    ApiPublicBadgeChar123mintChar125DotsvgRoute,
}

const ApiRouteWithChildren = ApiRoute._addFileChildren(ApiRouteChildren)

interface TapeRouteChildren {
  TapeEventIdRoute: typeof TapeEventIdRoute
}

const TapeRouteChildren: TapeRouteChildren = {
  TapeEventIdRoute: TapeEventIdRoute,
}

const TapeRouteWithChildren = TapeRoute._addFileChildren(TapeRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  AlertsRoute: AlertsRoute,
  ApiRoute: ApiRouteWithChildren,
  ChangelogRoute: ChangelogRoute,
  DisclaimerRoute: DisclaimerRoute,
  ExploreRoute: ExploreRoute,
  FlaggedRoute: FlaggedRoute,
  LeaderboardRoute: LeaderboardRoute,
  LoginRoute: LoginRoute,
  MethodologyRoute: MethodologyRoute,
  OperatorsRoute: OperatorsRoute,
  PricingRoute: PricingRoute,
  RegisterRoute: RegisterRoute,
  SignupRoute: SignupRoute,
  StatusRoute: StatusRoute,
  SubmitRoute: SubmitRoute,
  TapeRoute: TapeRouteWithChildren,
  AgentMintRoute: AgentMintRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
